### ISSUE TITLE
Error on first build after installing the starter

### ISSUE THREAD

**Issue by ronnidc** [gatsbyjs/gatsby-starter-kitchen-sink#2]
After running `gatsby new gatsby-kitchen-sink-site https://github.com/gatsbyjs/gatsby-starter-kitchen-sink`, `cd gatsby-kitchen-sink-site`, `npm i`, and `gatsby develop` or `gatsby build` I get the following error.

(I have a __gatsby-starter-default__ site running right beside with no problems). 

It might just be a question of updating dependencies. 

````
ERROR in ./~/gatsby/dist/utils/web-entry.js
Module not found: Error: Cannot resolve module '.gatsby-context' in /Users/username/Sites/gatsby-kitchen-sink-site/node_modules/gatsby/dist/utils
 @ ./~/gatsby/dist/utils/web-entry.js 26:18-44
^CMac:gatsby-kitchen-sink-site username$ gatsby build
Generating CSS
/Users/username/.npm-packages/lib/node_modules/gatsby-cli/index.js:166
    build(p).then(function () {
            ^

TypeError: Cannot read property 'then' of undefined
    at Command.<anonymous> (/Users/username/.npm-packages/lib/node_modules/gatsby-cli/index.js:166:13)
    at Command.listener (/Users/username/.npm-packages/lib/node_modules/gatsby-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/username/.npm-packages/lib/node_modules/gatsby-cli/node_modules/commander/index.js:635:12)
    at Command.parse (/Users/username/.npm-packages/lib/node_modules/gatsby-cli/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/Users/username/.npm-packages/lib/node_modules/gatsby-cli/index.js:209:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
````

**Comment by KyleAMathews** [comment]
This starter is more-or-less deprecated since it's for v0. Check out the starters for v1 at https://www.gatsbyjs.org/docs/gatsby-starters/
